### DISCUSSION TITLE
The piped pod is sometimes unstable when to cloning the git repo from GitHub

### DISCUSSION THREAD

**Discussion by ffjlabo** [pipe-cd/pipecd#4684] [Q&A]
The piped pod worked on k8s is sometimes unstable. It has restarted several times.
This is a log for it.
[extract-2023-11-17T06_05_58.835Z.csv](https://github.com/pipe-cd/pipecd/files/13435571/extract-2023-11-17T06_05_58.835Z.csv)

It also seems that piped was terminated after cloning the git repo from GitHub like this⇣
```
"2023-11-17T05:25:55.910Z",,,"2023/11/03 19:07:51 failed to clone git repo (failed to clone from remote: exit status 128)"
```

**Comment by ffjlabo** [comment]
When I checked the log, I found that the cause may be the ssh connection to GitHub and the connection being closed from the remote host, as shown below.

```
failed while checking applications in repo simply-kubernetes	{"error": "err: exit status 1, out: kex_exchange_identification: Connection closed by remote host\rConnection closed by 20.27.177.113 port 22\rfatal: Could not read from remote repository.Please make sure you have the correct access rightsand the repository exists."}
```

A case where a similar error occurred was posted in the discussion on GitHub itself.
https://github.com/orgs/community/discussions/55269

According to this, the problem is caused by communication being cut off due to firewalls or security groups.

**Comment by ffjlabo** [comment]
It would be nice to use **ssh over https** like below
https://github.com/orgs/community/discussions/55269#discussioncomment-6106315

```
Host github.com
    Hostname ssh.github.com
    Port 443
    User git
```

This can be realized by fixing to be able to set custom port  (related: https://github.com/pipe-cd/pipecd/issues/4674 )

```
apiVersion: pipecd.dev/v1beta1
kind: Piped
spec:
  projectID: xxx
  pipedID: xxxxxxx
  pipedKeyFile: /etc/piped-secret/piped-key
  # Write in a format like "host:443" because the communication is done via gRPC.
  apiAddress: "xxx"
  git:
    host: github.com
    hostName: ssh.github.com
    port: 443 # not yet
    sshKeyFile: /etc/piped-secret/ssh-key
```

or use "ssh over https" as default.
