### DISCUSSION TITLE
How ECS-related Design Should Be Like?

### DISCUSSION THREAD

**Discussion by t-kikuc** [pipe-cd/pipecd#4709] [Ideas]
## Why

- Backgrounds:
    - Types of use cases are increasing, as more users use PipeCD for ECS.
        - We cannot support all of ELB use cases yet.
        - We’d like to support other than ELB - Service Discovery, Service Connect, and App Mesh.
    - ECS itself has evolved.
- Problems:
    - It's difficult to add features or refactor due to complexity.
    - Configs(.yaml) are getting complicated or non-intuitive for users.

## What to discuss

- Share the points you'd like to improve, even if you don't have a clear solution.
  - Which codes should be refactored? Why?
     - e.g. We should create other stages, instead of using switch blocks. 
  - Which configs/stages should be redesigned? Why?
     - e.g. input `xxx` should be placed in the `yyy` section with `zzz` option.

**Comment by t-kikuc** [comment]
First opinion:   The stage `ECS_TRAFFIC_ROUTING` should be replaced by new stages.
For example,  `ELB_TRAFFIC_ROUTING`,  `SERVICE_DISCOVERY_TRAFFIC_ROUTING`, `APP_MESH_TRAFFIC_ROUTING`, and so on.

The reason:  Maintainability
   - Traffic routing depends on the type of networking and they use different logics and input configs.
      - e.g. We need to handle ELB APIs when using ELBs, but we don't need it when not using ELBs.
   - We should separate them so that we can easily/separately maintain traffic routing logics, even if AWS's spec is changed.

**Reply by khanhtc1202** [reply]
Agree with this, instead of making common use `ECS_TRAFFIC_ROUTING`, case-specific stage would be a great improvement 👍

**Reply by khanhtc1202** [reply]
Another point to note here is that I think the current pre-prepare (aka. `input` section of ECS application containing so much unrelated things)

```yaml
apiVersion: pipecd.dev/v1beta1
kind: ECSApp
spec:
  name: test
  input:
    serviceDefinitionFile: servicedef.yaml
    taskDefinitionFile: taskdef.yaml
    targetGroups:
      primary:
        targetGroupArn: arn:aws:elasticloadbalancing:ap-northeast-1:XXXX:targetgroup/ecs-tg-blue/YYYY
        containerName: web
        containerPort: 80
      canary:
        targetGroupArn: arn:aws:elasticloadbalancing:ap-northeast-1:XXXX:targetgroup/ecs-tg-green/ZZZZ
        containerName: web
        containerPort: 80
```

Targetgroup is the configuration for only ELB uses, so it would be better to move it to the `ELB_TRAFFIC_ROUTING` stage configuration. There is only one point here, which is we may need the targetgroup at the time we create taskset/task in stages before `ELB_TRAFFIC_ROUTING`, we should find a way to make this work smoothly 🤔

**Reply by khanhtc1202** [reply]
Should we draft some possible `ELB_TRAFFIC_ROUTING` configurations in case of using it? @t-kikuc

**Reply by t-kikuc** [reply]
> Targetgroup is the configuration for only ELB uses, so it would be better to move it to the ELB_TRAFFIC_ROUTING stage configuration.

That's a good point.

Now I wonder if the new `trafficRouting` section for ECS like k8s would help us.
I need to compare such options.

```yaml

apiVersion: pipecd.dev/v1beta1
kind: KubernetesApp
spec:
  name: mesh-istio-canary
  labels:
    env: example
    team: product
  pipeline:
    stages:
      - name: K8S_CANARY_ROLLOUT
        with:
          replicas: 10%
      - name: K8S_TRAFFIC_ROUTING
        with:
          primary: 90
          canary: 10
      - name: WAIT_APPROVAL
      - name: K8S_PRIMARY_ROLLOUT
      - name: K8S_TRAFFIC_ROUTING
        with:
          primary: 100
      - name: K8S_CANARY_CLEAN
  trafficRouting:   # HERE
    method: istio
    istio:
      host: mesh-istio-canary.default.svc.cluster.local

```

https://github.com/pipe-cd/pipecd/blob/301e3673f448b6a4d2e86921827b84c937d09002/examples/kubernetes/mesh-istio-canary/app.pipecd.yaml
