### DISCUSSION TITLE
Is Modification of Listener Rules Necessary for Canary Releases in ECS?

### DISCUSSION THREAD

**Discussion by moko-poi** [pipe-cd/pipecd#4724] [Ideas]
### Background:
In our current Canary Release approach for ECS, we can route traffic only to the DefaultListener. We are considering supporting the ability to route to specific listener rules.

### Problem:
With the existing implementation, there are multiple listener rules linked to a single listener. This becomes a challenge when requests are distributed based on path patterns, as our current approach does not support this.

### Rationale for Current Implementation:

Why have we implemented traffic routing only for the default listener till now?
What are the limitations or considerations that led to this decision?

### Proposed Solution - Adding getlistenerRuleArn:

By adding the getlistenerRuleArn function, we could potentially retrieve all rules associated with a listener.
Would this approach allow us to route Canary traffic based on specific listener rules?
What are the potential challenges or drawbacks of this implementation?

### Feedback and Suggestions:

We welcome input from the community on this issue.
Are there alternative solutions or considerations we should be aware of?
How can we effectively manage multiple listener rules in the context of Canary Releases?

**Comment by t-kikuc** [comment]
Thank you so much for creating the discussion 🎉  

I've just created the issue #4725 and attached the image to explain the use case as below:

> Why is this needed:
> - We need to specify the rules to modify other than default one.
>    For example, one listener has multiple listener rules and they have different path conditions and target services.
> - Now PipeCD updates only the Default rule.
>    So even if we want to modify the rule-web below, only the Default rule is modified.

![image](https://github.com/pipe-cd/pipecd/assets/97105818/82fcfcd4-7d78-4126-90b0-7ac50ad569d1)

**Comment by t-kikuc** [comment]
And I created PR https://github.com/pipe-cd/pipecd/pull/4726, seeing your PR https://github.com/pipe-cd/pipecd/pull/4668 as reference, thank you.

This is my idea in the PR, written here https://github.com/pipe-cd/pipecd/pull/4726#issuecomment-1859153392.
How about specifying the rules to modify in the `input` as below?

```yaml
apiVersion: pipecd.dev/v1beta1
kind: ECSApp
spec:
  input:
    serviceDefinitionFile: /path/to/servicedef.yaml
    taskDefinitionFile: /path/to/taskdef.yaml
    targetGroups:
      primary:
        targetGroupArn: arn:aws:elasticloadbalancing:xyz
        containerName: web
        containerPort: 80
    listenerRuleSelector:  # HERE.   If not specified, the default rule will be changed.
      listenerRuleArns:  # Which rules to modify.
        - arn:aws:elasticloadbalancing:ap-northeast-1:<account-id>:listener-rule/app/<elb-name>/xxx/yyy/zzz
        - arn:aws:elasticloadbalancing:ap-northeast-1:<account-id>:listener-rule/app/<elb-name>/xxx/yyy/zzz2
```

**Reply by moko-poi** [reply]
@t-kikuc
I've considered a similar implementation in the past. On August 31, 2023, during the PipeCD Public Meeting, we received feedback suggesting that instead of receiving configuration from app.pipecd.yaml, it would be preferable to integrate these changes into the existing ModifyListener structure. You can find the meeting notes and discussion here:

[Meeting Notes](https://docs.google.com/document/d/1AtE0CQYbUV5wLfvAcl9mo9MyTCH52BuU7AngVUvE7vg/edit)
[YouTube Video](https://www.youtube.com/watch?v=EFrOeYll9E4&t=10s)

Additionally, in a previous implementation attempt, we had set it up to receive configurations from piped, as you can see in this comment: https://github.com/pipe-cd/pipecd/pull/4540#issuecomment-1674256800.

**Reply by t-kikuc** [reply]
@moko-poi 
Thank you so much, I see.

You mean when `app.pipecd.yaml` is as below without listenerRuleArns, 
`Default` and `rule-hoge` should be modified because their target groups are the same as specified ones, right?

Then our goal is to modify not only the default action but also the rules which have the same target groups without specifying in `app.pipecd.yaml`, right?

```yaml
apiVersion: pipecd.dev/v1beta1
kind: ECSApp
spec:
  input:
    serviceDefinitionFile: /path/to/servicedef.yaml
    taskDefinitionFile: /path/to/taskdef.yaml
    targetGroups:
      primary:
        targetGroupArn: arn:aws:elasticloadbalancing:xyz  # arn of `t-kikuc-ecs-simple-target-group`
        containerName: web
        containerPort: 80
      canary:
        targetGroupArn: arn:aws:elasticloadbalancing:xyz  # arn of `t-kikuc-ecs-simple-target-group2`
        containerName: web
        containerPort: 80
```

![image](https://github.com/pipe-cd/pipecd/assets/97105818/9f3384fa-82ae-4549-b563-33665753cd95)
