### DISCUSSION TITLE
How about using AWS official structs in config for Lambda

### DISCUSSION THREAD

**Discussion by t-kikuc** [pipe-cd/pipecd#4798] [Ideas]
## What to add

- Migrate from function.yaml([FunctionManifestSpec](https://github.com/pipe-cd/pipecd/blob/9a298a8a7d2dcc4071ec2f63ab7c9d2fb1156ae5/pkg/app/piped/platformprovider/lambda/function.go#L60)) to aws-sdk's structs like:
  - [FunctionConfiguration](https://pkg.go.dev/github.com/aws/aws-sdk-go-v2/service/lambda@v1.53.1/types#FunctionConfiguration)
  - [FunctionCode](https://pkg.go.dev/github.com/aws/aws-sdk-go-v2/service/lambda@v1.53.1/types#FunctionCode)
defined in the package github.com/aws/aws-sdk-go-v2/service/lambda/types

## Background

- Currently, we use function.yaml, whose struct is defined by PipeCD, for configuring Lambda applications.

- The problem is that it's tough to follow the Lambda's new features, because we need to add options to the struct.

## Note

- It will be a breaking change since the configuration file will be changed.

**Comment by t-kikuc** [comment]
I found it is so difficult because: 

- Now we support fetching codes from Git repositories as below:  (critical)
https://github.com/pipe-cd/pipecd/blob/51a49f94927cc9b495d8d5ecb8518da0f29aaa9d/pkg/app/piped/executor/lambda/lambda.go#L355-L365
https://github.com/pipe-cd/pipecd/blob/51a49f94927cc9b495d8d5ecb8518da0f29aaa9d/pkg/app/piped/platformprovider/lambda/function.go#L123-L127

- Official structs `FunctionConfiguration` and `FunctionCode` do not have `Tags` field. (not critical)

**Reply by t-kikuc** [reply]
One idea is creating the wrapping struct like `LambdaManifest`

```go
type LambdaManifest struct{
    FunctionConfiguration types.FunctionConfiguration `json:"functionConfiguration"`
    FunctionCode          types.FunctionCode `json:"functionCode"`
    SourceCode           SourceCode `json:"sourceCode"`
}

 type SourceCode struct {  // existing one
 	Git  string `json:"git"` 
 	Ref  string `json:"ref"` 
 	Path string `json:"path"` 
 } 
```

The manifest would be like: 
```yaml
functionConfiguration: 
  functionName: my-func
  architectures:
    - xxx
    - yyy
  ephemeralStorage:
    size: xxx
  ...
functionCode:
  s3Bucket: xxx
  s3Key: yyy
  s3ObjectVersion: zzz
  ...
# sourceCode section is used if you deploy from Git directly
sourceCode:
  git: xxx
  ref: xxx
  path: xxx

```
