### DISCUSSION TITLE
Add option to ignore resource updates

### DISCUSSION THREAD

**Discussion by mk2taiga** [pipe-cd/pipecd#5654] [Ideas]
# Why
I want to temporarily change a k8s resource using the functionality of original custom controller. Therefore, there will be a temporary difference from Git.
The custom controller is also responsible for restoring the same state as Git.

I'm having a problem because if there is a release of the application on PipeCD while it is temporarily different from Git, it reverts back to the same state as Git.

# Idea
 I would like to add an option to ignore PipeCD updates if the k8s resource is given an any labels or annotations.
```yaml
# e.g.
apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-server
  annotations:
    pipecd.dev/ignore-sync: true
```
