### ISSUE TITLE
Pre-added stable chart repository

### ISSUE THREAD

**Issue by nakabonne** [pipe-cd/pipecd#1069]
**What would you like to be added**:
Currently, we have to configure helm settings in piped-config to use the stable repository. It would be nice to pre-added the repository by default.
```yaml
      chartRepositories:
        - name: stable
          address: https://kubernetes-charts.storage.googleapis.com
```

Btw, the stable and incubator repositories have moved to a new location. See: https://helm.sh/blog/new-location-stable-incubator-charts/

**Why is this needed**:
