### ISSUE TITLE
Templating commit message used by Event watcher

### ISSUE THREAD

**Issue by nakabonne** [pipe-cd/pipecd#1334]
**What would you like to be added**:
Currently, we can set the commit message used by event watcher.
It would be nice if the commit message can be templating.

```yaml
apiVersion: pipecd.dev/v1beta1
kind: Piped
spec:
  eventWatcher:
    repos:
      - repoId: foo
        commitMessage: update values {.Value} by {.EventName}
```
**Why is this needed**:
