### ISSUE TITLE
Proposal: Add support for K8S_TRAFFIC_MIRROR stage

### ISSUE THREAD

**Issue by nakabonne** [pipe-cd/pipecd#148]
**What would you like to be added**:
I'd love to propose to add `K8S_TRAFFIC_MIRROR` stage inspired by [the Traffic Mirroring feature of Flagger](https://docs.flagger.app/usage/deployment-strategies#blue-green-with-traffic-mirroring).
This stage copies the incoming request for Primary and sends it to Canary variant. It allows us to analyze blue/green deployment with any other providers than HTTP smoke tests.

The canonical use case is mirroring the Canary variant after we roll it out:

```yaml
# Pipeline for a Kubernetes application.
# This makes a progressive delivery with BlueGreen strategy.
# This also has a MIRRORING stage to copy the incoming request to primary and send it to canary, as well as ANALYSIS stage.
apiVersion: pipecd.dev/v1beta1
kind: KubernetesApp
spec:
  pipeline:
    stages:
      - name: K8S_CANARY_ROLLOUT
        with:
          replicas: 100%
      - name: K8S_TRAFFIC_MIRROR
        with:
          all: canary
      - name: ANALYSIS
        with:
          duration: 10m
          failureLimit: 2
          https:
            - template:
                name: grpc_error_rate_percentage
      - name: K8S_TRAFFIC_SPLIT
        with:
          all: canary
      - name: K8S_PRIMARY_UPDATE
      - name: K8S_TRAFFIC_SPLIT
        with:
          all: primary
      - name: K8S_CANARY_CLEAN
  trafficSplit:
    method: pod
```

Not to mention while it doesn't need to support by v1.alpha, it's worth considering from now on.
