### ISSUE TITLE
Add support for multiple YAML fields replacement using wildcard

### ISSUE THREAD

**Issue by nakabonne** [pipe-cd/pipecd#1748]
**What would you like to be added**:
From: https://github.com/pipe-cd/pipe/pull/1659#issuecomment-802830226
Currently, if we want to replace multiple fields using Event watcher, we use the `replacements` field.

Say we have a YAML file to be updated kind of like:

```yaml
# foo.yaml
foo:
  - name: hello
  - name: hello
```

In that case, what we can do is:
```yaml
apiVersion: pipecd.dev/v1beta1
kind: EventWatcher
spec:
  events:
    - name: event-1
      replacements:
        - file: foo.yaml
          yamlField: $.foo[0].name
        - file: foo.yaml
          yamlField: $.foo[1].name
```

But perhaps, it might be more helpful:
```yaml
apiVersion: pipecd.dev/v1beta1
kind: EventWatcher
spec:
  events:
    - name: event-1
      replacements:
        - file: foo.yaml
          yamlField: $.foo[*].name
```

**Why is this needed**:
