### ISSUE TITLE
kubectl does not use spec.cloudProviders[].config.kubeConfigPath

### ISSUE THREAD

**Issue by tennashi** [pipe-cd/pipecd#1946]
**What happened**:
When running `kubectl apply`, it seems to read the default kubeconfig and not the kubeconfig configured in `cloudProviders[].config.kubeConfigPath`.

https://github.com/pipe-cd/pipe/blob/2721206ea8b8ed484402ab75dfbafb9b999a8252/pkg/app/piped/cloudprovider/kubernetes/kubectl.go#L27-L31

`Kubectl.config` is defined, but

https://github.com/pipe-cd/pipe/blob/2721206ea8b8ed484402ab75dfbafb9b999a8252/pkg/app/piped/cloudprovider/kubernetes/kubectl.go#L33-L38

the value is `nil`.

https://github.com/pipe-cd/pipe/blob/2721206ea8b8ed484402ab75dfbafb9b999a8252/pkg/app/piped/cloudprovider/kubernetes/kubectl.go#L50-L54

And it's not even referenced when running `kubectl apply`.

**What you expected to happen**:

When applying, the following command will be executed.

```
kubectl apply --kubeconfig=/path/to/cloudproviders/kubeconfig -f -
```

**How to reproduce it**:

Configure the CloudProvider as follows

```
spec:
  cloudProviders:
    - name: kube
      type: KUBERNETES
      config:
        masterURL: https://X.X.X.X:6443
        kubeConfigPath: /etc/kube/kubeconfig
```

And mount kubeconfig to the specified path.

**Environment**:
- `piped` version: v0.9.11
- `control-plane` version: v0.9.11
- Others:
