### ISSUE TITLE
Make the .pipe/ directory deprecated

### ISSUE THREAD

**Issue by nakabonne** [pipe-cd/pipecd#2127]
**What would you like to be added**:
From https://github.com/pipe-cd/pipe/pull/2122

Currently, we have to place all configuration files for a git repo like `EventWathcher` and `AnalysisTemplate` under the `.pipe/` directory. But it's essentially unneeded.

It would be nice if we could place them anywhere and specify the paths. We have to add a new field for setting the place of the AnalysisTemplate file.

```yaml
apiVersion: pipecd.dev/v1beta1
kind: Piped
spec:
  analysis: # a new field is needed
    paths:
      - pipecd-config/dev/*.yaml
  eventWatcher:
    checkInterval: 30s
    gitRepos:
      - repoId: delivery
        commitMessage: Update values by Event watcher
        paths:
          - pipecd-config/dev/*.yaml
```

**Why is this needed**:
