### ISSUE TITLE
Invalid k8s annotations are not cause error and simply ignored.

### ISSUE THREAD

**Issue by Hosshii** [pipe-cd/pipecd#3242]
**What would you like to be added**:
k8s(and other kinds of application) spec validation.  

**Why is this needed**:
Following spec is invalid because while annotations' key and value must be string, ture is treated as bool.
```
apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    pipecd.dev/sync-by-replace: true # must be "true"
...
```
But the spec like this are not cause validation error, and the invalid annotations are simply ignored.
