### ISSUE TITLE
Unable to receive webhook notifications.

### ISSUE THREAD

**Issue by jo-jo-1217** [pipe-cd/pipecd#3277]
**What happened**.
https://pipecd.dev/docs-v0.21.x/operator-manual/piped/configuring-notifications/#sending-notifications-to-external-services-via-webhook
↑I set up webhook as per this page, but no notifications are flying.

**How to reproduce**.
Add the following to Pipecd.yaml

```
apiVersion: pipecd.dev/v1beta1
kind: Piped
spec:
  notifications:
    routes:
      # Sending all events an external service.
      - name: all-events-to-a-external-service
        receiver: a-webhook-service
    receivers:
      - name: a-webhook-service
        webhook:
          url: https://test.com/hooks/abcdefghijklmn
```

**Environment**:
- piped` Version.
  v0.22.0
- Control plane` version.
  v0.22.0

Translated with www.DeepL.com/Translator (free version)

**Comment by knanao** [comment]
Hi @jo-jo-1217 , thank you for your repot.
Can you check the log of piped? and are there any error in it?

**Comment by jo-jo-1217** [comment]
Hi @knanao 
There is no error log in piped...

**Comment by knanao** [comment]
@jo-jo-1217 
Oh, I see. Let me check this issue.
Just in cases, Could you please recheck outbound request?

**Comment by jo-jo-1217** [comment]
When I hit the curl command, the text jumped without any problem.
The URL seems to be correct...

**Comment by nghialv** [comment]
@jo-jo-1217 Thanks for your issue.

We have just checked this case but it worked normally as expected.

This is our Piped's configuration

``` yaml
  notifications:
    routes:
      - name: all-notifications
        receiver: webhook-service
    receivers:
      - name: webhook-service
        webhook:
          url: https://webhook.site/120d3814-c1e9-4b18-b197-4fc790afd6c4
```

And as you can see the event package has been delivered successfully.

https://webhook.site/#!/120d3814-c1e9-4b18-b197-4fc790afd6c4/524adebe-420b-486f-b936-b63b5c7d314a/1

So please recheck your configuration or try to update to use a newer version of PipeCD.
