### ISSUE TITLE
Support push events for actions-plan-preview

### ISSUE THREAD

**Issue by gkuga** [pipe-cd/pipecd#3481]
**What would you like to be added**:

* Support push events for actions-plan-preview

**Why is this needed**:

To run actions-plan-preview after automatically creating a PR as follows, supporting push event is needed. The reason why this is necessary is personal access token triggers PR events after create PRs but [GITHUB_TOKEN](https://docs.github.com/en/actions/using-workflows/triggering-a-workflow#triggering-a-workflow-from-a-workflow) doesn't do so.

```
on:
  push:
    branches: target-branch
jobs:
  create-pr:
    runs-on: ubuntu-latest
    if: "github.event.created"
    env:
      GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - uses: actions/checkout@v2
      - id: create-pr
        run: |
          PR=$(gh pr create --title "Update" --body "" | awk -F "/" '{print $NF}')
          echo "::set-output name=pull-request-number::$PR"
      - uses: pipe-cd/actions-plan-preview@v1.7.2
        with:
          address: ${{ secrets.PIPECD_API_ADDRESS }}
          api-key: ${{ secrets.PIPECD_PLAN_PREVIEW_API_KEY }}
          token: ${{ secrets.GITHUB_TOKEN }}
          pull-request-number: ${{ steps.create-pr.outputs.pull-request-number }}
```
