### ISSUE TITLE
Support authentication for pulling Remote Helm Chart in OCI registry

### ISSUE THREAD

**Issue by Szarny** [pipe-cd/pipecd#3638]
**What would you like to be added**:

Support authentication for pulling Remote Helm Chart in OCI registry.

**Why is this needed**:

Helm (>= v3.8.0) supports OCI for package distribution.
It's common to specify credentials before accessing the private OCI registry, but the current PipeCD cannot pass the credentials.

**Comment by Szarny** [comment]
**Design**
Configure *.pipecd.yaml as follows.

```yaml
apiVersion: pipecd.dev/v1beta1
kind: KubernetesApp
spec:
  ...
  input:
    helmChart:
      repository: oci://ghcr.io/pipe-cd
      name: chart/helloworld
      version: v0.30.0
    helmOptions:
      valueFiles:
        - values.yaml
      releaseName: helm-remote-chart
      authOptions:
        type: BASIC
        username: <USERNAME>
        password: <ENCRYPTED PASSWORD>
    helmVersion: 3.8.2
  description: ...
```
