### ISSUE TITLE
Potential directory traversal vuln due to Helm values file referencing outside of repo root

### ISSUE THREAD

**Issue by Szarny** [pipe-cd/pipecd#3719]
**What would you like to be added**:
​
According to [CVE-2022-24348](https://cve.mitre.org/cgi-bin/cvename.cgi?name=CVE-2022-24348), the past ArgoCD is vulnerable to directory traversal due to a Helm values file that references outside the repo root.
​
In the current PipeCD, we can similarly specify a values file that references outside the repo root of the Helm chart (and it will render correctly). Therefore, by preparing a crafted Helm Chart, there is a potential vulnerability that any YAML file on the host where Piped is running could be embedded in that chart. 
​
This would occur if the creator of a `.pipecd.yaml` knew the path to a YAML file containing sensitive information used by other applications.
​
The example is as follows.
​
```yaml
# Helm chart
apiVersion: v1
kind: ConfigMap
metadata:
  name: foo
data:
  foo: {{ .Values.data.secretData }}
```
​
```yaml
# .pipecd.yaml file
apiVersion: pipecd.dev/v1beta1
kind: KubernetesApp
spec:
  name: foo
  input:
    helmChart:
      path: path/to/helm-charts
    helmOptions:
      valueFiles:
        - ../../../../../../path/to/outside-of-helm-charts/secret.yaml
      releaseName: helm-remote-chart
    helmVersion: 3.8.2
```
​
```yaml
# secret.yaml file
apiVersion: v1
kind: Secret
type: Opaque
data:
  secretData: SECRET_DATA
```
​
**Why is this needed**:
To eliminate directory traversal vulnerabilities.
