### ISSUE TITLE
Display wrong cloud provider in Show Piped config dialog

### ISSUE THREAD

**Issue by Szarny** [pipe-cd/pipecd#3731]
**What happened**:

Whatever Cloud Provider is specified in piped config, it's displayed on web console as Kubernetes.
![image](https://user-images.githubusercontent.com/26561120/172108202-723e98d9-db63-496c-9c1f-116eb7e6251d.png)

**What you expected to happen**:

Configs are displayed according to the specified Cloud Provider.

**How to reproduce it**:

Specify a Cloud Provider other than Kubernetes and open the Show piped config dialog.

**Environment**:
- `piped` version: 
- `control-plane` version:
- Others:

**Comment by Szarny** [comment]
There may be a bug when cloning piped config.

Piped config
```yaml
cloudProviders:
- name: kubernetes-dev
  type: KUBERNETES
  config:
    kubeConfigPath: /path/to/.kube/config
- name: terraform-dev
  type: TERRAFORM
  config:
    vars:
      - "project=pipecd"
```

Debug code
```go
fmt.Printf("[DEBUG1] %+v\n", cfg.CloudProviders)

cloneCfg, err := cfg.Clone()
if err != nil {
    return err
}

fmt.Printf("[DEBUG2] %+v\n", cloneCfg.CloudProviders)
```

Result
```
[DEBUG1] [{Name:kubernetes-dev Type:KUBERNETES KubernetesConfig:0xc0005266c0 TerraformConfig:<nil> CloudRunConfig:<nil> LambdaConfig:<nil> ECSConfig:<nil>} {Name:terraform-dev Type:TERRAFORM KubernetesConfig:<nil> TerraformConfig:0xc00019fa70 CloudRunConfig:<nil> LambdaConfig:<nil> ECSConfig:<nil>}]

[DEBUG2] [{Name:kubernetes-dev Type:KUBERNETES KubernetesConfig:0xc00078eea0 TerraformConfig:<nil> CloudRunConfig:<nil> LambdaConfig:<nil> ECSConfig:<nil>} {Name:terraform-dev Type:KUBERNETES KubernetesConfig:0xc00078ef00 TerraformConfig:<nil> CloudRunConfig:<nil> LambdaConfig:<nil> ECSConfig:<nil>}]
```
