### ISSUE TITLE
Can't register ECS task definition by piped on EKS kubernetes

### ISSUE THREAD

**Issue by jedipunkz** [pipe-cd/pipecd#3810]
**What happened**:

I would like to deploy ECSApp with pipecd and piped on EKS.

pipecd is already deployed. and I tried to boot piped on EKS k8s 1.22 with such configuration.

```yaml
apiVersion: pipecd.dev/v1beta1
kind: Piped
spec:
  projectID: quickstart
  pipedID: ******
  pipedKeyFile: /etc/piped-secret/piped-key
  apiAddress: pipecd:8080
  git:
    sshKeyFile: /etc/piped-secret/ssh-key
  repositories:
    - repoId: pipecd-sandbox
      remote: git@github.com:foo/bar.git
      branch: main
  syncInterval: 1m
  cloudProviders:
    - name: ecs-dev
      type: ECS
      config:
        region: ap-northeast-1
        credentialsFile: /etc/piped-secret/credentials-file
        profile: sandbox
```

and tried to deploy piped such command

```shell
helm upgrade -i piped oci://ghcr.io/pipe-cd/chart/piped --version=v0.34.0 --namespace=pipecd \
  --set-file config.data=./piped-config-k8s.yaml \
  --set-file secret.data.piped-key=./piped-key-file \
  --set-file secret.data.ssh-key=/Users/thirai/.ssh/pipecd \
  --set-file secret.data.credentials-key=/Users/thirai/.aws/credentials \
  --set args.insecure=true
```

successfully deployed piped on k8s. and I created Application on Pipecd Web UI, then I get these logs.

```
Failed to register ECS task definition of family commandexec: failed to register ECS task definition of family commandexec: operation error ECS:     RegisterTaskDefinition, failed to sign request: failed to retrieve credentials: no EC2 IMDS role found, operation error ec2imds: GetMetadata, req    uest canceled, context deadline exceeded
```

my ~/.aws/credentials has permission to register task definition. 

**What you expected to happen**:

I expected that my piped register task definition and with ecs service throught app.pipecd.yaml at my git repo.

**How to reproduce it**:

also I tried to use service account such command, but same issue I got.

```shell
helm upgrade -i piped oci://ghcr.io/pipe-cd/chart/piped --version=v0.34.0 --namespace=pipecd \
  --set-file config.data=./piped-config-k8s.yaml \
  --set-file secret.data.piped-key=./piped-key-file \
  --set-file secret.data.ssh-key=/Users/thirai/.ssh/pipecd \
  --set args.insecure=true \
  -set serviceAccount.create=false \
  -set serviceAccount.name=infrabot-pods-sa
```

**Environment**:
- `piped` version: v0.34.0
- `control-plane` version: v0.34.0
- Others: EKS k8s 1.22, helm v3.9.1

**Comment by khanhtc1202** [comment]
Hi @jedipunkz, thanks for using PipeCD 🥰

About your case, could you try the following command
```
aws ecs register-task-definition --cli-input-json file://path/to/taskdef.json
```
Just want to ensure that the credentials file you're using is valid and has enough permission for that action.

And besides, could you check the k8s Secret for credentials, looks like you use a wrong path name in your Piped configuration

instead of 
```
  cloudProviders:
    - name: ecs-dev
      type: ECS
      config:
        region: ap-northeast-1
        credentialsFile: /etc/piped-secret/credentials-file
        profile: sandbox
```
should be
```
  cloudProviders:
    - name: ecs-dev
      type: ECS
      config:
        region: ap-northeast-1
        credentialsFile: /etc/piped-secret/credentials-key
        profile: sandbox
```
Since at this line
```
--set-file secret.data.credentials-key=/Users/thirai/.aws/credentials
```
a secret file created under `credentials-key` name.
