### ISSUE TITLE
no data point compare by Datadog Analysis Provider 

### ISSUE THREAD

**Issue by jedipunkz** [pipe-cd/pipecd#3812]
**What happened**:

I m trying to use Datadog Analysis Provider with ECS. 

This is my piped configuration.

```yaml
apiVersion: pipecd.dev/v1beta1
kind: Piped
spec:
  projectID: quickstart
  pipedID: *******-****-****-***-*******
  pipedKeyFile: /etc/piped-secret/piped-key
  apiAddress: pipecd:8080
  git:
    sshKeyFile: /etc/piped-secret/ssh-key
  repositories:
    - repoId: pipecd-sandbox-canary
      remote: git@github.com:jedipunkz/pipecd-sandbox-canary.git # this is private repo
      branch: main
  syncInterval: 1m
  cloudProviders:
    - name: sandbox-ecs
      type: ECS
      config:
        region: ap-northeast-1
        credentialsFile: /etc/piped-secret/credentials-key
        profile: sandbox
  analysisProviders:
    - name: sandbox-datadog
      type: DATADOG
      config:
        apiKeyFile: /etc/piped-secret/datadog-api-key
        applicationKeyFile: /etc/piped-secret/datadog-application-key
```

and I deployed piped with helm on EKS k8s cluster.

```shell
helm upgrade -i piped oci://ghcr.io/pipe-cd/chart/piped --version=v0.34.0 --namespace=pipecd \
  --set-file config.data=./piped-config-k8s-canary.yaml \
  --set-file secret.data.piped-key=./piped-key-file \
  --set-file secret.data.ssh-key=/Users/thirai/.ssh/pipecd \
  --set-file secret.data.credentials-key=/Users/thirai/.aws/credentials \
  --set args.insecure=true \
  --set-file secret.data.datadog-api-key=/Users/thirai/rf/infra/pipecd/datadog-api-key \
  --set-file secret.data.datadog-application-key=/Users/thirai/rf/infra/pipecd/datadog-application-key
```

My `app.piped.yaml` has such ANALYSIS setting.

```yaml
      - name: ANALYSIS
        with:
          duration: 30m
          metrics:
            - strategy: THRESHOLD
              provider: sandbox-datadog
              interval: 5m
              expected:
                max: 0.01
              query: |
                aws.applicationelb.active_connection_count
                /
                aws.applicationelb.request_count
```

This query is just for testing and no meaning, and this query always output 0.2 percent over. So I expect that fail with this ANALYSIS setting.

![スクリーンショット 2022-07-20 16 28 36](https://user-images.githubusercontent.com/1404689/179922983-e96746ab-ae58-4f07-a018-8f38b165f0db.png)

This query is base AWS Integration on Datadog. These output Metrics always delayed and not evenly interval.

and Pipeline `ANALYSIS` Step outputs these logs... `This analysis stage will be skipped since there was no data point to compare`. Then, ANALYSIS step successeded and my canary release deployment complete with success.

- Why does not this fail?
- or Is this query correct?
- (and I think it's less risky not to skip with no data point. Should I create a enhancement ticket?)

```
[2022-07-20 16:22:32 +09:00]
[metrics-0] Run query: "aws.applicationelb.active_connection_count / aws.applicationelb.request_count ", in range: {2022-07-20 07:17:32.998019089 +0000 UTC m=+8876.296627933 2022-07-20 07:22:32.998019089 +0000 UTC m=+9176.296627933}
[2022-07-20 16:22:33 +09:00]
[metrics-0] This analysis stage will be skipped since there was no data point to compare
[2022-07-20 16:22:33 +09:00]
[metrics-0] The query result is expected one
[2022-07-20 16:27:32 +09:00]
[metrics-0] Run query: "aws.applicationelb.active_connection_count / aws.applicationelb.request_count ", in range: {2022-07-20 07:22:32.998370772 +0000 UTC m=+9176.296979600 2022-07-20 07:27:32.998370772 +0000 UTC m=+9476.296979600}
[2022-07-20 16:27:33 +09:00]
[metrics-0] This analysis stage will be skipped since there was no data point to compare
[2022-07-20 16:27:33 +09:00]
[metrics-0] The query result is expected one
```

**What you expected to happen**:

This ANALYSIS pipeline step will fail and ROLLBACK. Because this query is always over 0.02%.

**How to reproduce it**:

- I created query with Datadog Metrics UI
- Increased interval and duration

**Environment**:
- `piped` version: v0.34.0
- `control-plane` version: v0.34.0
- Others:
  - EKS k8s 1.22
  - ECS

**Comment by jedipunkz** [comment]
I tried this query, but result is same.

```yaml
             query: |
               sum:aws.applicationelb.active_connection_count{*}.as_count()
               /
               sum:aws.applicationelb.request_count{*}.as_count()
```

and also, I tried to use metrics via datadog-agent (not AWS Integration)

```yaml
              query: sum:system.cpu.idle{*}
```

This query failed as expected.

```

**Comment by jedipunkz** [comment]
Now I tried such ANALYSIS settings with 10m interval. (Datadog Metcis Interval time with AWS Integration is 5m)

```yaml
      - name: ANALYSIS
        with:
          duration: 30m
          metrics:
            - strategy: THRESHOLD
              provider: rf-sandbox-datadog
              interval: 10m
              expected:
                max: 0.01
              # query: sum:system.cpu.idle{*}
              query: |
               sum:aws.applicationelb.active_connection_count{*}.as_count()
               /
               sum:aws.applicationelb.request_count{*}.as_count()
```

This query failed as expected.

```
[2022-07-21 11:14:44 +09:00]
[metrics-0] Failed because it found a data point (timestamp: "54521-08-16 19:20:00 UTC", value: 0.32722832722832723) that is outside the expected range (<= 0.01). Performed query: "sum:aws.applicationelb.active_connection_count{*}.as_count() / sum:aws.applicationelb.request_count{*}.as_count() "
[2022-07-21 11:14:44 +09:00]
Analysis failed: analysis 'metrics-0' failed because the failure number exceeded the failure limit (0)
```

But with this setting, only one data is analyzed in one analysis interval. I may need to consider using datadog custom metrics 🤔
