### ISSUE TITLE
Add the way to access git repository by using Personal Access Token(PAT)

### ISSUE THREAD

**Issue by kevin-namba** [pipe-cd/pipecd#4106]
**What would you like to be added**:
We would like to make the option to access repository by using Personal Access Token(PAT) in addition to using SSH key.
```yaml
apiVersion: pipecd.dev/v1beta1
kind: Piped
spec:
  git:
     # sshKeyFile: {PATH _TO_SSH_KEY_FILE}
     personalAccessToken:
        userName: <user-name>
        userToken: <user-token>
```
**Why is this needed**:
Now Pipecd uses SSH key to access repositories. But we can not control access policies to repositories when using SSH keys .
We should use Github Personal Access Token instead of SSH key.

ex. fluxCD adopt PAT to access repositories. https://fluxcd.io/flux/get-started/
