### ISSUE TITLE
Enable to load application used manifests/configs from Git

### ISSUE THREAD

**Issue by khanhtc1202** [pipe-cd/pipecd#4188]
**What would you like to be added**:

Be able to load application-used manifests/configs from the same Git with applications' manifests in case of ECS/CloudRun application

**Why is this needed**:

For K8s applications, we can easily address this issue by using manifests of kind ConfigMap which is stored under the same Git directory as other applications' manifests. For ECS/CloudRun there is no simple way to archive that (for example, we have to inject those manifests into the application containers by mounting it via `containerDefinitions.secrets` in the case of the ECS application).

**Comment by kevin-namba** [comment]
How about that runs cronjob to manage secrets manager
```mermaid
sequenceDiagram
    autonumber
		participant g as github
    participant c as cron job
		participant p as piped
		participant e as ECS
    participant s as secrets manager
c ->> g: detect config change
g ->> c: read config
c ->> s: update secrets manager 
c ->> p: notify change
p ->> g: read repo and rewrite arn of secrets
p ->> e: deploy infrastructure
s ->> e: read secrets
```

**Comment by nghialv** [comment]
@kevin-namba I think this issue should only focus on non-sensitive data like config file or a plain-text file stored in Git.
What we want is a way to allow loading of config files in container when it starts running, e.g. via environment variable or argument.

``` yaml
apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: hello
spec:
  template:
    spec:
      containers:
      - image: gcr.io/google-samples/hello-app:1.0
        args:
        - config-data={{ .file "hello-app-config.yaml" }}
```
