### ISSUE TITLE
Enable to ignore manifests' fields from drift detection

### ISSUE THREAD

**Issue by khanhtc1202** [pipe-cd/pipecd#4190]
**What would you like to be added**:

**Why is this needed**:

Some autogenerated fields in k8s manifests changed on each rerun, thus users want to ignore them from the drift detection feature. Would be best if we can make it available via application config.

**Comment by golemiso** [comment]
How about definining a new annotation  `pipecd.dev/ignore-drift-detection-on`?
```
spec:
  template:
    metadata:
      annotations:
        deployedAt: {{ now | unixEpoch | quote }} # regenerate every run
        pipecd.dev/ignore-drift-detection-on: |
          ["spec.template.metadata.annotations.deployedAt"]
```
