### ISSUE TITLE
Enable sudo commands in the custom templating install script

### ISSUE THREAD

**Issue by kevin-namba** [pipe-cd/pipecd#4193]
**What would you like to be added**:
Enable sudo commands in the install script for custom templating tools.
```
apiVersion: pipecd.dev/v1beta1
kind: KubernetesApp
spec:
  input:
      installScriptTemplate: |
        sudo apt install foobar
```

**Why is this needed**:
https://github.com/pipe-cd/pipecd/pull/4156 supports to install templating tools other than kustomize and helm, but we can not use sudo command in the install script.
