### ISSUE TITLE
Make sync policy configurable

### ISSUE THREAD

**Issue by nakabonne** [pipe-cd/pipecd#421]
**What would you like to be added**:
```yaml
apiVersion: pipecd.dev/v1beta1
kind: KubernetesApp
spec:
  sync:
    prune: true
```
**Why is this needed**:

/assign @nghialv
