### ISSUE TITLE
PlanPreview is not triggered when just updating terraform module

### ISSUE THREAD

**Issue by knanao** [pipe-cd/pipecd#4247]
**What happened**:

**What you expected to happen**:

**How to reproduce it**:

**Environment**:
- `piped` version:
- `control-plane` version:
- Others:

**Comment by knanao** [comment]
This could resolve with the following configuration.

```
apiVersion: pipecd.dev/v1beta1
kind: TerraformApp
spec:
  ...
  trigger:
    onCommit:
      paths:
        - "__PATH__TO_MODULE_DIR__"
```
