### ISSUE TITLE
support enable piped to add asdf plugin with git repo

### ISSUE THREAD

**Issue by kevin-namba** [pipe-cd/pipecd#4312]
**What would you like to be added**:
enable piped to add asdf plugin with git repo
```
externalTools:
  - package: "aws-sam-cli"
    version: "1.77.0"
```
```
externalTools:
  - asdfPluginName: aws-sam-cli
    asdfPluginRepo: https://github.com/amrox/asdf-pyapp.git
    version: 1.77.0
```
**Why is this needed**:
