### ISSUE TITLE
[piped] Create a new pull request feature

### ISSUE THREAD

**Issue by sivchari** [pipe-cd/pipecd#4360]
**What would you like to be added**:

Now, event-watcher of Piped's feature doesn't create a new pull request, when it pushes new commit to repository.  But a number of repository prohibits the push to default branch. So, I propose the new feature to create a pull. This feature is optional, so if someone doesn't want this feature, they can ignore it. But if this idea is accepted, we will think a lot of things (e.g. About /pkg/git). So I want to discuss about this feature is needed or not.

**Why is this needed**:

**Comment by nnnkkk7** [comment]
How about implementing it this way?

**Overview**
 Add an optional flag to `Git` in the following configuration to indicate whether or not to create a new branch.
https://pipecd.dev/docs/user-guide/managing-piped/configuration-reference/#git

**Details**
- This filed is defined as `enableNewBranch` and the type is bool.
- The argument of `newBranch` in the `CommitChanges` method is currently passed a fixed false, so we will pass `enableNewBranch` in config.
https://github.com/pipe-cd/pipecd/blob/master/pkg/app/piped/eventwatcher/eventwatcher.go#L642
- In the `CommitChanges` method, if `newBranch` is true, Git client checkouts a new branch. So we should need a some kind of branch name to checkout.
Therefore, if `enableNewBranch` is true, Git client makes a new branch named {eventName}-{uuid} (uuid is generated by already depended google/uuid lib).
 https://github.com/pipe-cd/pipecd/blob/master/pkg/app/piped/eventwatcher/eventwatcher.go#L596

If ok, I would like to create a new PR related with this. wdyt ?

**Comment by sivchari** [comment]
I agree with your opinion, but I would like to discuss if the field name is optimal with @nnnkkk7 and @khanhtc1202 .
And do you think where it's better that uuid is generated ? I think uuid should be generated by a uuid-generator-client which piped-agent newly has. That why, Git client has no side-effect to test.

**Comment by nnnkkk7** [comment]
@sivchari @khanhtc1202
Thanks!
I think it is better from a testing point of view to create a uuid-generator-client, but currently other parts of the program also directly use google/uuid methods, so I would like to make it a separate scope for this Issue. And  uuid-generator-client would make it easier to test other parts, so it would be good to set up such an issue.

**Comment by nnnkkk7** [comment]
I created PR about this issue.
https://github.com/pipe-cd/pipecd/pull/4395

**Comment by khanhtc1202** [comment]
@nnnkkk7 @sivchari Thanks so much for your contribution 🙌 
Sorry for my late on design comments, the current implementation is acceptable. But there is a bit "UX kind" problem here I want to make it clear.

If we enable this configuration in piped.spec.git, then at the time when users configure for their piped, they have to decide do they want that config or not, and they may don't even know about the event watcher. That's why I think we should move this configuration to event watcher related part, which should be

In case of using event watcher independent configuration (ref: https://pipecd.dev/docs/user-guide/event-watcher/#use-the-pipe-directory)
```yaml
apiVersion: pipecd.dev/v1beta1
kind: EventWatcher
spec:
  events:
    - name: helloworld-image-update
      createMergeRequest: true
      replacements:
        - file: helloworld/deployment.yaml
          yamlField: $.spec.template.spec.containers[0].image
```

In case of using application configuration config
```yaml
apiVersion: pipecd.dev/v1beta1
kind: KubernetesApp
spec:
  name: helloworld
  eventWatcher:
    - matcher:
        name: helloworld-image-update
      handler:
        type: GIT_UPDATE
        config:
          createMergeRequest: true
          replacements:
            - file: deployment.yaml
              yamlField: $.spec.template.spec.containers[0].image
```

wdyt?
