### ISSUE TITLE
Better way to specify version for templating tools

### ISSUE THREAD

**Issue by khanhtc1202** [pipe-cd/pipecd#4382]
**What would you like to be added**:

```yaml
apiVersion: pipecd.dev/v1beta1
kind: KubernetesApp
spec:
  input:
    namespace: sample
    helmVersion: 3.8.2
    kustomizeVersion: 5.0.3
...
```

This configuration should install helm version v3.8.2 and kustomize version v5.0.3, both in the piped container environment, but it's not work like that now.

**Why is this needed**:

Kustomize can be configured to be used with helm via `enable-helm` & `helm-command` flags. The PipeCD currently supports [kustomizeOptions](https://pipecd.dev/docs/user-guide/configuration-reference/#kubernetesdeploymentinput:~:text=No-,kustomizeOptions,-map%5Bstring%5Dstring), which is a map of options for kustomize build command, so basically users can use `enable-helm` if they want.

The point to note here is that even if they use `helm-command` to specify helm version they want to use with kustomize build, there is no way to have that version of helm command via PipeCD configuration currently.
