### ISSUE TITLE
Control-Plane, Decrease cronjob time to collect deployment data

### ISSUE THREAD

**Issue by jz543fm** [pipe-cd/pipecd#4391]
**What would you like to be added**:

Decreased time to check deployment data via crojob time collect much sooner than with actual setting: `30 * * * *`
 
pod: `pipecd-ops-*`

log:

 `start running insight collector    {"config": {"application":{"enabled":true,"schedule":"0 * * * *"},"deployment":{"enabled":true,"schedule":"30 * * * *","chunkMaxCount" │
│ :1000}}}`

**Why is this needed**:

Faster error tracing

**Comment by jz543fm** [comment]
Ok, I resolved this, fixed by adding this to control-plane

```
  InsightCollector:
    deployment:
      enabled: true
      schedule: "* * * * *"
    application:
      enabled: true
      schedule: "* * * * *"
```
