### ISSUE TITLE
Should we flatten the eventWatcher configuration?

### ISSUE THREAD

**Issue by khanhtc1202** [pipe-cd/pipecd#4402]
**What would you like to be added**:

The current eventWatcher config in app configuration look like this

```yaml
apiVersion: pipecd.dev/v1beta1
kind: KubernetesApp
spec:
  name: helloworld
  eventWatcher:
    - matcher:
        name: helloworld-image-update
      handler:
        type: GIT_UPDATE
        config:
          replacements:
            - file: deployment.yaml
              yamlField: $.spec.template.spec.containers[0].image
```

the matcher and handler make it look complicated, I want to make it flatten as the old EventWatcher kind configuration

```yaml
apiVersion: pipecd.dev/v1beta1
kind: KubernetesApp
spec:
  name: helloworld
  eventWatcher:
    - name: helloworld-image-update
      type: GIT_UPDATE
      labels:
        env: dev
      config:
        replacements:
          - file: deployment.yaml
            yamlField: $.spec.template.spec.containers[0].image
```

If we don't have plan for multi handlers for single matcher each event, I think flatten configuration is easier to get and remember. wdyt?

**Why is this needed**:
