### ISSUE TITLE
Managed certificates and backend config are missing with helm upgrade

### ISSUE THREAD

**Issue by kentakozuka** [pipe-cd/pipecd#4413]
**What happened**:

When running `helm upgrade pipecd` with both gateway and grafana managed certificate and backend config, pipecd's objects cannot be applied.

This is because `{{-` remove new line on the left side and the templating result will be;

```
# Source: pipecd/templates/backend-config.yaml
apiVersion: cloud.google.com/v1beta1
kind: BackendConfig
metadata:
  name: pipecd
spec:
  iap:
    enabled: true
    oauthclientCredentials:
      secretName: pipecd-iap---
apiVersion: cloud.google.com/v1beta1
kind: BackendConfig
metadata:
  name: pipecd-grafana
spec:
  iap:
    enabled: true
    oauthclientCredentials:
      secretName: pipecd-monitoring-iap
```

**What you expected to happen**:

```
# Source: pipecd/templates/backend-config.yaml
apiVersion: cloud.google.com/v1beta1
kind: BackendConfig
metadata:
  name: pipecd
spec:
  iap:
    enabled: true
    oauthclientCredentials:
      secretName: pipecd-iap
---
apiVersion: cloud.google.com/v1beta1
kind: BackendConfig
metadata:
  name: pipecd-grafana
spec:
  iap:
    enabled: true
    oauthclientCredentials:
      secretName: pipecd-monitoring-iap
```

**How to reproduce it**:

**Environment**:
- `piped` version:
- `control-plane` version:
- Others:
