### ISSUE TITLE
doc: Installation instruction with docker

### ISSUE THREAD

**Issue by nakabonne** [pipe-cd/pipecd#451]
**What would you like to be added**:
Something like this:

```bash
docker run --rm \
  -v $(pwd):/etc/piped-secret \
  -v ~/.kube/config:/root/.kube/config \
  gcr.io/pipecd/piped:v0.1.6-8-g734d974 \
  piped \
  --metrics \
  --enable-default-kubernetes-cloud-provider \
  --log-encoding=humanize \
  --control-plane-address=dev.pipecd.dev:443 \
  --config-file=/etc/piped-secret/piped-config.yaml
```

Preparing a piped configuration file as the following:
```yaml
apiVersion: pipecd.dev/v1beta1
kind: Piped
spec:
  projectID: YOUR_PROJECT_ID
  pipedID: YOUR_PIPED_ID
  pipedKeyFile: /etc/piped-secret/piped-key
  syncInterval: 1m
  git:
    sshKeyFile: /etc/piped-secret/ssh-key
  repositories:
    - repoId: REPO_ID_OR_NAME
      remote: git@github.com:YOUR_GIT_ORG/YOUR_GIT_REPO.git
      branch: master
  cloudProviders:
    - name: kubernetes-default
      type: KUBERNETES
      config:
        kubeconfigPath: /root/.kube/config

```

**Why is this needed**:
