### ISSUE TITLE
Make it possible to webhook notification for Rolling Back event

### ISSUE THREAD

**Issue by GotoRen** [pipe-cd/pipecd#4547]
**What would you like to be added**:

After a deployment failed and is rolling back, a functionality is needed to notify the event status related to `DEPLOYMENT_ROLLING_BACK`.

**Why is this needed**:

By adding events for PipeCD [Configuring notifications](https://pipecd.dev/docs-dev/user-guide/managing-piped/configuring-notifications/) to the `spec.notifications.routes.events[]` field in piped config, any service can receive deployment events.

For example, configure it as follows.

```yaml
spec:
  notifications:
    routes:
      - name: sample
        events:
          - DEPLOYMENT_ROLLING_BACK
          - DEPLOYMENT_SUCCEEDED
          - DEPLOYMENT_FAILED
          - DEPLOYMENT_CANCELLED
        receiver: sample-receiver
    receivers:
      - name: sample-receiver
        ...
        ...
```

However, in the current implementation, even if you set `DEPLOYMENT_ROLLING_BACK`, any services cannot receive the rolling back event.
This is because the current event handler is only checked by `DEPLOYMENT_SUCCEEDED`, `DEPLOYMENT_FAILED`, and `DEPLOYMENT_CANCELLED`.

FYI:
- https://github.com/pipe-cd/pipecd/blob/master/pkg/model/notificationevent.pb.go#L44-L47
- https://github.com/pipe-cd/pipecd/blob/master/pkg/app/piped/controller/scheduler.go#L614-L655
