### ISSUE TITLE
[ECS] 503 error occurred while PrimaryRollout because it deletes the canary too early

### ISSUE THREAD

**Issue by t-kikuc** [pipe-cd/pipecd#4710]
**What happened**:

The `ECS_PRIMARY_ROLLOUT` stage deleted the old task sets **including the canary task set**.
-> The traffic-receiving target group lost instances to route traffic.
-> `503 Service Temporarily Unavailable` happened until the `ECS_TRAFFIC_ROUTING` stage ended in a Blue/Green case.

**What you expected to happen**:

The `ECS_PRIMARY_ROLLOUT` stage should delete only the old PRIMARY task sets and keep the canary task set alive.

We need to fix the below:
https://github.com/pipe-cd/pipecd/blob/301e3673f448b6a4d2e86921827b84c937d09002/pkg/app/piped/executor/ecs/ecs.go#L242-L249

**How to reproduce it**:

When you use `ECS_PRIMARY_ROLLOUT` for ECS deployments, it will happen.
(503 happens in Blue/Green)

**Environment**:
- `piped` version:  v0.45.4
- `control-plane` version:   v0.46.0-rc0-11-g301e367
- Others:  `app.pipecd.yaml` was as below (masked):

```
apiVersion: pipecd.dev/v1beta1
kind: ECSApp
spec:
  name: ecs-elb-bg-issue
  input:
    serviceDefinitionFile: servicedef.yaml
    taskDefinitionFile: taskdef.yaml
    targetGroups:
      primary:
        targetGroupArn: arn:aws:elasticloadbalancing:ap-northeast-1:<account-id>:targetgroup/t-kikuc-ecs-simple-target-group/326xxxxxxxxxxxxx
        containerName: web
        containerPort: 80
      canary:
        targetGroupArn: arn:aws:elasticloadbalancing:ap-northeast-1:<account-id>:targetgroup/t-kikuc-ecs-simple-target-group2/a0bxxxxxxxxxxxxx
        containerName: web
        containerPort: 80
  pipeline:
    stages:
      - name: ECS_CANARY_ROLLOUT
        with:
          scale: 100
      - name: WAIT_APPROVAL
      - name: ECS_TRAFFIC_ROUTING
        with:
          canary: 100
      - name: WAIT_APPROVAL
      - name: ECS_PRIMARY_ROLLOUT
      - name: WAIT_APPROVAL
      - name: ECS_TRAFFIC_ROUTING
        with:
          primary: 100
      - name: WAIT_APPROVAL
      - name: ECS_CANARY_CLEAN
```

**Diagram**
Current: 
![current](https://github.com/user-attachments/assets/1e88d3de-52fd-437b-8f37-1022450f999b)

Desired:
![desired](https://github.com/user-attachments/assets/ea9a519c-54bd-4a12-a710-368578528fa6)

**Comment by t-kikuc** [comment]
In the `ECS_CANARY_CLEAN` stage after `ECS_PRIMARY_ROLLOUT`, 
I failed to delete the canary task set because it's already removed.

The logs in Control Plane: 

> Failed to clean CANARY task set <taskset-arn>: failed to delete ECS task set <taskset-arn>: operation error ECS: DeleteTaskSet, https response error StatusCode: 400, RequestID: <request-id>, TaskSetNotFoundException: Unable to find task set with id <taskset-id> on service ecs-bg-broken-service-1.

**Comment by t-kikuc** [comment]
It's easy to modify not deleting canary while `ECS_PRIMARY_ROLLOUT`, 
but it's much easier to modify not deleting all old tasksets while `ECS_PRIMARY_ROLLOUT`.

I wonder which is better...

**Comment by armistcxy** [comment]
Newcomer but I have some observations and thoughts for this issue and also the ECS deployment strategy when using PipeCD

First, I still don't know why we in current `ECS_PRIMARY_ROLLOUT` stage we need to delete the previous tasksets. I acknowledge that previous taskset workload still consumes resources and cost money, but isn't the stage name is PRIMARY_ROLLOUT
=> which I believe should focus only on create new taskset and promote it as the new primary

This should be seperated into 2 stages `PRIMARY_ROLLOUT` and `CANARY_CLEAN`

however, there a simple solution for this, to avoid affecting already in-used pipelines, we can add one field `DeletePrevTasksets bool`  in the primary roll out stage option (=> the default value of bool is false so this won't affect old pipelines => new pipeline can leverages this)  https://github.com/pipe-cd/pipecd/blob/faa25da9cfb6fd8aa3c835079de531889669564c/pkg/config/application_ecs.go#L120C1-L122C2

Another point is the lack of terminologies and different behavior between EXTERNAL and ECS deployment controller can also cause mistakes sometimes. For example, in `ECS` type, primary will receive all the traffics but with `EXTERNAL`, primary taskset means nothing except the "PRIMARY" tag. Also pipecd doesn't have things like baketime, deployment baketime, etc. also this can work around with script run stage and wait stage but require understanding pipecd at some extent

**Comment by armistcxy** [comment]
With the newest implementation (Primary Rollout only delete old primary taskset instead of deleting all previous task sets), I think this issue won't happen again

Proof with a manual test with a process requests constantly to the ALB during pipeline process  

(Code: https://gist.github.com/armistcxy/7a24c1f46253bf1a9251a3adb4a62b1a)

Stage specifications
```yaml
  pipeline:
    rollback: false
    stages:
      - name: ECS_CANARY_ROLLOUT
        with:
          scale: 50
      - name: ECS_TRAFFIC_ROUTING
        with:
          canary: 20
      - name: WAIT_APPROVAL
        with:
          approvers:
            - hello-pipecd
          minApproveNum: 1
          timeout: 2h
      - name: ECS_PRIMARY_ROLLOUT
      - name: ECS_TRAFFIC_ROUTING
        with:
          primary: 100
      - name: ECS_CANARY_CLEAN
```

Result

```
========== Summary ==========
Total:      591 requests
Success:    591
Errors:     0
Version 1:  184
Version 2:  407
Downtime:   0s
Result:     ZERO DOWNTIME
```
