### ISSUE TITLE
PipeCD gets diff with bool value in Cloud Run manifets

### ISSUE THREAD

**Issue by tetsuya28** [pipe-cd/pipecd#4790]
**What happened**: With Cloud Run application, when we set a bool value for env, PipeCD gets diff the env, like following.
Manifest is
```yaml
apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: xxx
spec:
  template:
    spec:
      containers:
        - name: xxx
          env:
            - name: XXX
              value: false
```

PipeCD console is 
```diff
      spec:
        containers:
          - env:
              -
                #spec.template.spec.containers.0.env.10.value
-               value: false
+               value: <bool Value>
```

**What you expected to happen**:

**How to reproduce it**:

**Environment**:
- `piped` version: `v0.44.2`
- `control-plane` version: `v0.46.0`
- Others:
