### ISSUE TITLE
Use current deployment context in SCRIPT_RUN stage

### ISSUE THREAD

**Issue by minhquang4334** [pipe-cd/pipecd#4814]
**What would you like to be added**:
Use current deployment context (like DeploymentTrigger, DeploymentStatus, etc.) in SCRIPT_RUN stage.
refs: https://pipecd.dev/docs-v0.46.x/user-guide/managing-application/customizing-deployment/script-run/

**Why is this needed**:
Since we don't know about the current deployment, it is difficult to write a script for customization of the deployment process. 

This is similar to GitHubAction, where we can access job and step contexts through a defined property.
refs: https://docs.github.com/en/actions/learn-github-actions/contexts#job-context

**Comment by peaceiris** [comment]
I look forward to this feature!

In our use case, we want to get the `Summary` including a docker image tag.

**Comment by ffjlabo** [comment]
@minhquang4334 @peaceiris 
Sorry for the late response 🙏 

We can realize it by adding the default environment variable for `SR_XX` (like `SR_DEPLOYMENT_ID`).
How about this?

```
apiVersion: pipecd.dev/v1beta1
kind: KubernetesApp
spec:
  name: script-run
  labels:
    env: example
    team: product
  pipeline:
    stages:
      - name: K8S_CANARY_ROLLOUT
        with:
          replicas: 10%
      - name: WAIT
        with:
          duration: 10s
      - name: SCRIPT_RUN
        with:
          run: |
            echo $SR_DEPLOYMENT_ID
      - name: K8S_PRIMARY_ROLLOUT
      - name: K8S_CANARY_CLEAN
```
