### ISSUE TITLE
PipeCD Control Plane displayed unknown field error when config `recreate` for ECSApplication

### ISSUE THREAD

**Issue by minhquang4334** [pipe-cd/pipecd#4909]
**What happened**:
PipeCD Control Plane displayed an error message `Failed to load application config: json: unknown field "recreate"` when our ECSApplication was configured with "recreate: true" on quickSync.
https://pipecd.dev/docs-v0.47.x/user-guide/configuration-reference/#ecs-application

**What you expected to happen**:
`recreate` is an expected field, so the above error should not occur.

**How to reproduce it**:
Our ECSApp config
```yaml
apiVersion: pipecd.dev/v1beta1
kind: ECSApp
spec:
  name: dev-myapp
  labels:
    env: dev
    layer: backend
  input:
    serviceDefinitionFile: servicedef.yaml
    taskDefinitionFile: taskdef.yaml
  attachment:
    sources:
      config: app-config.yaml
    targets:
      - taskdef.yaml
  description: |
    desc-myapp
  quickSync:
    recreate: true

```

**Environment**:
- `piped` version:	v0.47.0
- `control-plane` version: 
- Others:

**Comment by t-kikuc** [comment]
@minhquang4334 
Thank you for reporting.

I'm sorry but I could not reproduce the problem.
I used piped v0.47.0 and my app.pipecd.yaml was: 
```yaml
apiVersion: pipecd.dev/v1beta1
kind: ECSApp
spec:
  name: ecs-4909-recreate
  input:
    serviceDefinitionFile: servicedef.yaml
    taskDefinitionFile: taskdef.yaml
    targetGroups:
      primary:
        targetGroupArn: <MASKED>
        containerName: web
        containerPort: 80
  description: |
    desc-example
  quickSync:
    recreate: true
```

Would you please re-confirm your yaml's indents?


BTW, when I used the following wrong yaml, the same error occured.

```yaml
spec:
  ...
  quickSync:
  recreate: true. # NOT INDENTED
```



![image](https://github.com/pipe-cd/pipecd/assets/97105818/dd465a2f-3033-4811-a8eb-d0b37803ae79)
