### ISSUE TITLE
can't delete the resources when enabling the prune option in K8S_PRIMARY_ROLLOUT after deleting the manifests

### ISSUE THREAD

**Issue by ffjlabo** [pipe-cd/pipecd#4933]
**What happened**:

When I use the PipelineSync, including `K8S_PRIMARY_ROLLOUT`, sometimes the pruning doesn't work.

**What you expected to happen**:

It would be nice to delete resources when enabling the prune option in K8S_PRIMARY_ROLLOUT after deleting the manifests.

**How to reproduce it**:

Using the config below, do the step-by-step instructions.

1. Delete target manifests 
2. set `prune: true` for the `K8S_PRIMARY_ROLLOUT` stage
3. re PipelineSync

```
apiVersion: pipecd.dev/v1beta1
kind: KubernetesApp
spec:
  name: canary
  labels:
    env: example
    team: product
  planner:
    alwaysUsePipeline: true
  pipeline:
    stages:
      # Deploy the workloads of CANARY variant. In this case, the number of
      # workload replicas of CANARY variant is 10% of the replicas number of PRIMARY variant.
      - name: K8S_CANARY_ROLLOUT
        with:
          replicas: 10%
      # Wait 10 seconds before going to the next stage.
      - name: WAIT
        with:
          duration: 10s
      # Update the workload of PRIMARY variant to the new version.
      - name: K8S_PRIMARY_ROLLOUT
        with:
          prune: true
      # Destroy all workloads of CANARY variant.
      - name: K8S_CANARY_CLEAN
  description: |
    This app demonstrates how to deploy a Kubernetes app by Canary strategy without requering any mesh.\
    References: [adding a new app](https://pipecd.dev/docs/user-guide/managing-application/adding-an-application/), [app configuration](https://pipecd.dev/docs/user-guide/configuration-reference/)
```

target resource
```
- deployment
```

**Environment**:
- `piped` version:
- `control-plane` version:
- Others:
