### ISSUE TITLE
Support for PipeCD to delete a resource in CloudRunApp

### ISSUE THREAD

**Issue by ucpr** [pipe-cd/pipecd#5007]
**What would you like to be added**:

I want to delete a resource, like the following, in CloudRunApp.

```yaml
apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: SERVICE_NAME
spec:
...
```

In a Kubernetes application, in order to remove a resource, we need to put `QuickSync.prune` or `PipelineSync.prune` in the PipeCD application manifest.
It would be nice to have the same configuration for CloudRunApp.

**Why is this needed**:

Without this feature, developers need to delete Cloud Run on Google Cloud Console manually.
