### ISSUE TITLE
Support multiple value updates in EventWatcher

### ISSUE THREAD

**Issue by tom-256** [pipe-cd/pipecd#5088]
**What would you like to be added**:

Enhance the [event watcher](https://pipecd.dev/docs-v0.48.x/user-guide/event-watcher/) feature to support multiple data updates in a single event registration, with the ability to associate specific data with specific file updates.
 

Example configuration:
```yaml
eventWatcher:
  - matcher:
      name: multi-update
      labels:
        env: dev
        appName: helloworld
    handler:
      type: GIT_UPDATE
      config:
        replacements:
          - file: deployment.yaml
            yamlField: $.spec.template.spec.containers[0].image
            dataKey: image
          - file: config.yaml
            yamlField: $.data.version
            dataKey: version
          - file: ingress.yaml
            yamlField: $.spec.rules[0].host
            dataKey: hostname
```
Example command:
```sh
pipectl event register \
    --address=CONTROL_PLANE_API_ADDRESS \
    --api-key=API_KEY \
    --name=multi-update \
    --labels env=dev,appName=helloworld \
    --data image=gcr.io/pipecd/helloworld:v0.2.0 \
    --data version=1.2.3 \
    --data hostname=example.com
```

**Why is this needed**:

- Flexibility: Users often need to update multiple related configurations simultaneously
  - For example:
    - Update the image tag version
    - Declare the current image tag version as an environment variable
- Efficiency: Allowing multiple updates in a single event reduces the number of separate events that need to be registered and processed.
