### ISSUE TITLE
[ECS] Support definable pipeline stage for ECS_SYNC

### ISSUE THREAD

**Issue by minhquang4334** [pipe-cd/pipecd#5374]
**What would you like to be added**:
- Support definable pipeline stage for ECS_SYNC

**Why is this needed**:
- Currently PipeCD only provides some stages for canary releases
  - refs: https://pipecd.dev/docs-v0.48.x/user-guide/managing-application/defining-app-configuration/ecs/ 
- During ECS application deployment, we cannot configure SCRIPT_RUN due to the ECS_SYNC completed event

```yaml
 pipeline:
    stages:
      - name: ECS_SYNC
      - name: SCRIPT_RUN
        with:
          env:
            MSG: "execute script2"
          run: |
            echo $MSG
            sleep 10     
```
