### ISSUE TITLE
Unintended revert deployment

### ISSUE THREAD

**Issue by nakabonne** [pipe-cd/pipecd#557]
**What happened**:
In case that the revert commit for a different app is the latest commit, an unintended deployment is performed when the sync button is pressed.
![image](https://user-images.githubusercontent.com/19730728/88765672-c8699280-d1b1-11ea-9b3d-011a9a7cc29b.png)

**What you expected to happen**:

**How to reproduce it**:
Setting commit matcher for appA:
```yaml
apiVersion: pipecd.dev/v1beta1
kind: KubernetesApp
spec:
  commitMatcher:
    sync: "^Revert"
```

Then, pushing a commit which reverts the changes of appB with a message "Revert foo".

**Environment**:
- `piped` version:
- `control-plane` version:
- Others:
