### ISSUE TITLE
specifying Helm version doesn't seem to be used in plan-preview

### ISSUE THREAD

**Issue by JohnTitor** [pipe-cd/pipecd#5635]
**What happened**:
plan-preview currently fails if we use config/templates described in the "How to reproduce it" section.

The error itself is:
```
Reason: failed while planning, unable to run kustomize template: exit status 1: Error: Error: template: datadog/templates/gke_autopilot_allowlist_synchronizer.yaml:1:48: executing "datadog/templates/gke_autopilot_allowlist_synchronizer.yaml" at <include "gke-autopilot-workloadallowlists-enabled" .>: error calling include: template: datadog/templates/_helpers.tpl:74:23: executing "gke-autopilot-workloadallowlists-enabled" at <len $nodes>: error calling len: reflect: call of reflect.Value.Type on zero Value
```

This is caused by older Helm, like v3.8.0. Helm v3.17.0, for instance, treats it without any failure.

The mysterious part of this problem is it still occurs even if we have a config like `helmVersion: 3.17.0` in pipecd.yaml. We thought it was used in plan-preview.

I thought https://github.com/pipe-cd/pipecd/issues/4382 fixed the problem but for some reason our plan preview is still broken. Maybe we've misconfigured something or implementation still needs a tweak.

(note: we haven't checked if this problem only occur on plan-preview or not.)

**What you expected to happen**: should succeed plan-preview (and any other procedure)

**How to reproduce it**:
1. prepare a PipeCD config like:
  ```yaml
  apiVersion: pipecd.dev/v1beta1
kind: KubernetesApp
spec:
  name: datadog-agent
  input:
    kustomizeVersion: 5.6.0
    kustomizeOptions:
      enable-helm: ""
    helmVersion: 3.17.0
  ```
2. prepare a Kustomize config like:
```yaml
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
helmCharts:
  - name: datadog
    releaseName: datadog-agent
    repo: https://helm.datadoghq.com
    version: 3.102.0
```
3. Run `pipectl plan-preview` or trigger the plan-preview action against it

**Environment**:
- `piped` version: v0.50.2
- `control-plane` version: v0.50.2
- Others:
  - datadog-agent chart: v3.98.0 or higher
  - Kustomize: v5.6.0
  - Helm: v3.17.0
