### ISSUE TITLE
Support Cloud Run Job

### ISSUE THREAD

**Issue by ren510dev** [pipe-cd/pipecd#5812]
**What happened**:

When trying to deploy a Cloud Run Job with PipeCD, the following error is returned: `spec.template.spec.containers` was missing

It appears that the current implementation of PipeCD only supports deploying Cloud Run Services, which follows the format of `spec.template.spec.containers`.

- https://github.com/pipe-cd/pipecd/blob/b5d9fc976d26000f08c8ab3e3927d4f674f1d595/pkg/app/piped/platformprovider/cloudrun/servicemanifest.go#L169-L174

However, Cloud Run Jobs use a different structure for the container specification: `spec.template.spec.template.spec.containers`.
As a result, PipeCD does not handle the second-level `template.spec` required for Jobs, the deployment fails.

**What you expected to happen**:

Both Cloud Run Services and Jobs can be deployed using PipeCD.

**How to reproduce it**:

Prepare a manifest for a Cloud Run Job and try to deploy it using PipeCD.

ex.

```yaml
apiVersion: run.googleapis.com/v1
kind: Job
metadata:
  name: sample-job
  namespace: sample-ns
spec:
  template:
    metadata:
      labels:
        name: sample-job
      annotations:
        run.googleapis.com/client-name: gcloud
        run.googleapis.com/client-version: 510.0.0
        run.googleapis.com/execution-environment: gen2
    spec:
      taskCount: 1
      template:
        spec:
          containers:
            - image: your-image
```

**Environment**:

- `piped` version: v0.51.2
- `control-plane` version: v0.51.2
