### ISSUE TITLE
Decide how to check if the body is expected one

### ISSUE THREAD

**Issue by nakabonne** [pipe-cd/pipecd#65]
https://github.com/pipe-cd/pipe/blob/c7fa9f48c8b151dc0790b9e7d2ae055632db53b1/pkg/app/piped/analysisprovider/http/http.go#L66-L69

## Idea1
Compare with the specific value in the JSON body, like Argo Rollouts: https://argoproj.github.io/argo-rollouts/features/analysis/#web-metrics

```yaml
          https:
            - url: https://canary-endpoint.dev
              method: GET
              expectedCode: 200
              expectedValue: true
              jsonPath: "{$.results.ok}"
```

Pros:
- simple

Cons:
- The response must be JSON format

## links
- https://argoproj.github.io/argo-rollouts/features/analysis/#web-metrics
- https://flagger.app/usage/webhooks.html
