### ISSUE TITLE
Support stage to make pseudo requests

### ISSUE THREAD

**Issue by nakabonne** [pipe-cd/pipecd#794]
**What would you like to be added**:
The analysis stage cannot perform normally for applications that are receiving constant traffic. We can resolve it by adding a stage that runs a given number of requests.

It's enough to perform https://github.com/rakyll/hey internally. Configuration for testers will be something like:

```yaml
apiVersion: pipecd.dev/v1beta1
kind: KubernetesApp
spec:
  pipeline:
    stages:
      - name: SEND_REQUESTS
        with:
          # Testers keep sending requests until the end of the analysis stage.
          https:
            - target: http://helloworld:9898/foo
              method: POST
              body: '{foo: 1}'
              # Timeout for each request.
              timeout: 10s
              # Number of workers to run concurrently
              worker: 50
              # In queries per second (QPS) per worker. Default is no rate limit.
              rateLimit: 10
          grpcs:
            - 
```

**Why is this needed**:
